### ISSUE TITLE
foto 

### ISSUE THREAD

**Issue by reins5** [bootpi/Floorplan#2]
tu dici:
Alla fine di tutto dovrete avere tot foto per tot luci e in più 2 foto, una di giorno e una di sera.
Puoi spiegarti meglio?
Grazie

**Comment by bootpi** [comment]
si certo facciamo un esempio:
Supponiamo che controlli in tutto 10 luci con Hassio, devi fare 10 foto (con l'orario di sera cioè 20.30) una per luce (una sola luce deve essere accesa per foto) e in più dovrai fare 2 foto una di giorno (12.30) e una di sera (20.30)
In tutto avrai 12 foto.... Capito?

**Comment by reins5** [comment]
provo....... e poi come fai a dare azione on/off ad uno switch.
grazie

**Comment by bootpi** [comment]
tap_action:
    action: toggle

**Comment by mamos76** [comment]
Purtroppo continuo a non capire... le foto le devo fare alla stanza con il cellulare ? Una con la luce accesa e una con la luce spenta? Gli orari cosa c’entrano. A cosa mi servono le foto delle stanze se poi devo fare a mano la piantina delle stanze tramite sweethome?

**Comment by bootpi** [comment]
No assolutamente. Crea la piantina con sweethome e poi con lo strumento "📸" fai la foto alla vista 3d

**Comment by bootpi** [comment]
Lo strumento ha proprio questa icona 📸

**Comment by mamos76** [comment]
Ok quindi disegno la piantina della stanza, aggiungo i vari mobili ecc ecc. poi faccio la foto con lo strumento che mi hai detto te ad ogni stanza creata. Ne faccio sempre due per ogni luce presente, una mi servirà con la luce accesa e una mi servirà per la luce spenta. 
Quindi se in camera ho una sola luce farò 2 foto. Se ne ho 2 farò 4 foto. 
Le foto saranno però tutte uguali inizialmente sarà successivamente che n’è userò una per la luce accesa e una per la luce spenta...
Ho capito tutto in maniera corretta?

**Comment by bootpi** [comment]
No!
1°: crea la foto di sera a tutta la casa
2°: crea la foto di giorno a tutta la casa
3°: crea la foto di sera con la prima luce accesa a tutta la casa
4°: spengi la luce di prima ne accendi un'altra e fai la foto a tutta la casa con l'orario di sera
5°: spengi la luce e ne accendi un'altra e fai la foto a tutta la casa con l'orario di sera
 E così via poi segui la guida

**Comment by mamos76** [comment]
Quindi faccio una sola planimetria con tutte le stanze insieme e poi uso lo strumento foto per le varie luci che ho. La luce la imposto accesa da sweethome Ok?

**Comment by bootpi** [comment]
si

**Comment by reins5** [comment]
Fin qua ci siamo, ora non riesco a capire come fare il ritaglio delle stanze in modo da poterle accendere e spegnere in modo che ogni stanza sia indipendente.

**Comment by bootpi** [comment]
non devi fare il taglio delle stanze ma dividere la foto in due zone (giorno e notte) con GIMP
