### ISSUE TITLE
utenti

### ISSUE THREAD

**Issue by reins5** [bootpi/Floorplan#4]
citazione............ custom_header serve per impostare il display in kiosk_mode che permette di nascondere la barra laterale e la barra delle pagine di hassio cosi da avere un'inquadratura totale per il tablet. Come potete vedere ho imposta la kiosk_mode solo all'utente tablet ed al user_agent.
domanda: devo attivare un utente chiamato "tablet"?
domanda: che intendi per "user_agent"?

grazie

**Comment by bootpi** [comment]
Mi pare che sia chiaro.. Per user agent se vedi bene c'è il link
