### ISSUE TITLE
meteo

### ISSUE THREAD

**Issue by reins5** [bootpi/Floorplan#7]
salve non riesco a visualizzare la card del meteo 
grazie

**Comment by bootpi** [comment]
Hai cambiato l'entità?

**Comment by reins5** [comment]
Non ho cambiato nulla, ho notato in realtà che la scritta è di colore nero e non si vede con lo sfondo nero.
Forse come dici tu il problema è nell'entità.
 entity: weather.roma
come carichi questa entità?
grazie
![Screenshot_20200420-091658](https://user-images.githubusercontent.com/58402555/79738058-89978700-82fc-11ea-8d31-9943e7658d76.jpg)

**Comment by reins5** [comment]
Non ho cambiato nulla, ho notato in realtà che la scritta è di colore nero e non si vede con lo sfondo nero.
Forse come dici tu il problema è nell'entità.
 entity: weather.roma
come carichi questa entità?
grazie

**Comment by bootpi** [comment]
Devi cambiare coloro alla scritta
Sotto a weather__info aggiungi
color: #ffffff;
